name: 'Terrarium - Setup'
description: 'Sets up Terrarium CLI in your GitHub Actions workflow.'
author: 'digitalkaoz'
branding:
  icon: upload-cloud
  color: purple

inputs:
  version:
    description: 'the cli version'
    default: '1.3.2'
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        curl -L -o $GITHUB_WORKSPACE/terrarium.tar.gz https://github.com/terrarium-tf/cli/releases/download/v${{ inputs.version }}/terrarium_${{ inputs.version }}_Linux_arm64.tar.gz
        tar -xvzf $GITHUB_WORKSPACE/terrarium.tar.gz
        rm $GITHUB_WORKSPACE/terrarium.tar.gz
        chmod a+x $GITHUB_WORKSPACE/terrarium
      shell: bash
    - run: |
        echo "$GITHUB_WORKSPACE/terrarium" >> $GITHUB_PATH
        echo "$RUNNER_WORKSPACE/$(basename $GITHUB_REPOSITORY)/terrarium" >> $GITHUB_PATH
      shell: bash 
    - run: |
        echo $PATH
        terrarium --version
      shell: bash
