name: 'Terrarium - Setup'
description: 'Sets up Terrarium CLI in your GitHub Actions workflow.'
author: 'digitalkaoz'
inputs:
  version:
    description: 'the cli version'
    default: '1.0.0'
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        curl -L -o $GITHUB_WORKSPACE/terrarium.zip https://github.com/terrarium-tf/cli/releases/download/v${{ inputs.version }}/terrarium_${{ inputs.version }}_Linux_arm64.tar.gz
        unzip -qq $GITHUB_WORKSPACE/terrarium.zip -d $GITHUB_WORKSPACE/bin
        rm $GITHUB_WORKSPACE/terrarium.zip
        chmod a+x $GITHUB_WORKSPACE/bin/terrarium
      shell: bash
    - run: |
        echo "$GITHUB_WORKSPACE/bin/terrarium" >> $GITHUB_PATH
        echo "$RUNNER_WORKSPACE/$(basename $GITHUB_REPOSITORY)/bin/terrarium" >> $GITHUB_PATH
      shell: bash 
    - run: |
        echo $PATH
        terrarium --version
      shell: bash
